import type { Metadata, Viewport } from "next";
import { Instrument_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

/* ── the two voices ───────────────────────────────────────────────────────
   Instrument Sans carries everything that is prose or interface. It is a
   slightly narrow grotesque with flat, cut terminals and small apertures,
   which is what lets a headline hold tight tracking at 4.5rem without the
   letterforms going soft, and what keeps a 13px table label legible where a
   rounder face turns to grey. It replaces Geist, which is drawn to
   disappear — the right call for a framework's own docs, the wrong one for a
   product that has to look like somebody designed it.

   IBM Plex Mono is the metering voice: every figure, threshold, field name
   and unit on this site. It is deliberately not chosen as a code font. Its
   numerals carry real contrast — a slashed zero, a flagged one, a $ that
   survives at 10px — so a column of money reads as an instrument's readout
   rather than as a terminal dump.

   Neither is given a weight where the face is variable: the whole axis ships
   as one file, so a heading can sit at 580 instead of snapping to the nearest
   static cut.
   ────────────────────────────────────────────────────────────────────── */

const sans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument",
  display: "swap",
});

const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-plex",
  // Plex Mono is not variable, so the cuts are named explicitly.
  weight: ["400", "500", "600"],
  display: "swap",
});

// The "Aperture" logo kit, served straight out of /public.
const KIT = "/planckspace-logo-kit";
const OG_IMAGE = `${KIT}/png/og-1200x630.png`;

export const metadata: Metadata = {
  metadataBase: new URL("https://planckspace.dev"),
  title: {
    default: "PlanckSpace: Every AI team, more efficient",
    template: "%s | PlanckSpace",
  },
  description:
    "PlanckSpace measures, optimizes, and verifies what your team's AI coding costs across Claude Code, Cursor, Windsurf, and Antigravity. Per-developer and per-repo attribution, waste found and priced, and savings verified from your own telemetry. Metadata only, so your code never leaves your machine.",
  keywords: [
    "AI coding costs",
    "Claude Code spend tracker",
    "Cursor spend analytics",
    "AI token usage dashboard",
    "AI budget management for teams",
    "engineering cost visibility",
    "AI coding observability",
    "cost per shipped session",
    "AI spend reconciliation",
  ],
  authors: [{ name: "PlanckSpace" }],
  openGraph: {
    title: "PlanckSpace: Every AI team, more efficient",
    description:
      "Measure what AI coding costs across Claude Code, Cursor, Windsurf, and Antigravity, cut the waste it finds, and verify the savings from your own telemetry, all without touching your code.",
    type: "website",
    url: "https://planckspace.dev",
    siteName: "PlanckSpace",
    images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: "PlanckSpace" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "PlanckSpace: Every AI team, more efficient",
    description:
      "Measure what AI coding costs across Claude Code, Cursor, Windsurf, and Antigravity, cut the waste it finds, and verify the savings from your own telemetry, all without touching your code.",
    images: [OG_IMAGE],
  },
  // Tab icons come from /favicon (generated by the frontend's scripts/gen-favicons.mjs)
  // rather than straight from the kit: the kit's favicons are the bare ink mark on
  // transparency, which disappears against a dark browser tab strip. These are the
  // mark on an ink tile.
  icons: {
    icon: [
      { url: "/favicon/favicon.ico", sizes: "any" },
      { url: "/favicon/planckspace-favicon.svg", type: "image/svg+xml" },
      { url: "/favicon/favicon-48.png", sizes: "48x48", type: "image/png" },
      { url: "/favicon/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon/favicon-16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: { url: "/favicon/apple-touch-icon.png", sizes: "180x180" },
  },
  manifest: "/site.webmanifest",
};

/* Next injects width=device-width, initial-scale=1 by default; this export is
   here for the two things it does not do.

   viewportFit "cover" lets the page paint under a notch and the home-indicator
   bar, which is what makes env(safe-area-inset-*) return anything other than 0.
   The container and the mobile nav panel both read those insets, so without
   this the site is letterboxed on every modern iPhone in landscape.

   maximumScale is deliberately absent. Capping it stops pinch-zoom, which is
   an accessibility failure; the iOS focus-zoom it is usually there to suppress
   is fixed properly in globals.css by sizing form controls at 16px. */
export const viewport: Viewport = {
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0c0d12" },
  ],
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable} h-full`}>
      <body className="antialiased min-h-full bg-[var(--page)] text-[var(--ink)]">
        {children}
      </body>
    </html>
  );
}
