import type { Metadata, Viewport } from "next";
import { Geist, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  weight: ["400", "500"],
  display: "swap",
});

// The "Aperture" logo kit, served straight out of /public.
const KIT = "/planckspace-logo-kit";
const OG_IMAGE = `${KIT}/png/og-1200x630.png`;

export const metadata: Metadata = {
  metadataBase: new URL("https://planckspace.dev"),
  title: {
    default: "PlanckSpace: Every AI team, more efficient",
    template: "%s | PlanckSpace",
  },
  description:
    "PlanckSpace measures, optimizes, and verifies what your team's AI coding costs across Claude Code, Cursor, Windsurf, and Antigravity. Per-developer and per-repo attribution, waste found and priced, and savings verified from your own telemetry. Metadata only, so your code never leaves your machine.",
  keywords: [
    "AI coding costs",
    "Claude Code spend tracker",
    "Cursor spend analytics",
    "AI token usage dashboard",
    "AI budget management for teams",
    "engineering cost visibility",
    "AI coding observability",
    "cost per shipped session",
    "AI spend reconciliation",
  ],
  authors: [{ name: "PlanckSpace" }],
  openGraph: {
    title: "PlanckSpace: Every AI team, more efficient",
    description:
      "Measure what AI coding costs across Claude Code, Cursor, Windsurf, and Antigravity, cut the waste it finds, and verify the savings from your own telemetry, all without touching your code.",
    type: "website",
    url: "https://planckspace.dev",
    siteName: "PlanckSpace",
    images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: "PlanckSpace" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "PlanckSpace: Every AI team, more efficient",
    description:
      "Measure what AI coding costs across Claude Code, Cursor, Windsurf, and Antigravity, cut the waste it finds, and verify the savings from your own telemetry, all without touching your code.",
    images: [OG_IMAGE],
  },
  // Tab icons come from /favicon (generated by the frontend's scripts/gen-favicons.mjs)
  // rather than straight from the kit: the kit's favicons are the bare ink mark on
  // transparency, which disappears against a dark browser tab strip. These are the
  // mark on an ink tile.
  icons: {
    icon: [
      { url: "/favicon/favicon.ico", sizes: "any" },
      { url: "/favicon/planckspace-favicon.svg", type: "image/svg+xml" },
      { url: "/favicon/favicon-48.png", sizes: "48x48", type: "image/png" },
      { url: "/favicon/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon/favicon-16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: { url: "/favicon/apple-touch-icon.png", sizes: "180x180" },
  },
  manifest: "/site.webmanifest",
};

/* Next injects width=device-width, initial-scale=1 by default; this export is
   here for the two things it does not do.

   viewportFit "cover" lets the page paint under a notch and the home-indicator
   bar, which is what makes env(safe-area-inset-*) return anything other than 0.
   The container and the mobile nav panel both read those insets, so without
   this the site is letterboxed on every modern iPhone in landscape.

   maximumScale is deliberately absent. Capping it stops pinch-zoom, which is
   an accessibility failure; the iOS focus-zoom it is usually there to suppress
   is fixed properly in globals.css by sizing form controls at 16px. */
export const viewport: Viewport = {
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0c0d12" },
  ],
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geist.variable} ${jetbrains.variable} h-full`}>
      <body className="antialiased min-h-full bg-[var(--page)] text-[var(--ink)]">
        {children}
      </body>
    </html>
  );
}
