import type { Metadata } from "next";
import { Geist, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  weight: ["400", "500"],
  display: "swap",
});

// The "Aperture" logo kit, served straight out of /public.
const KIT = "/planckspace-logo-kit";
const OG_IMAGE = `${KIT}/png/og-1200x630.png`;

export const metadata: Metadata = {
  metadataBase: new URL("https://planckspace.dev"),
  title: {
    default: "PlanckSpace — Spend management for AI-assisted engineering",
    template: "%s — PlanckSpace",
  },
  description:
    "PlanckSpace meters every token your team spends in Claude Code, Cursor, Windsurf, and Antigravity — one shared dashboard for cost visibility, waste detection, and invoice reconciliation. Metadata only — your code never leaves your machine.",
  keywords: [
    "AI coding costs",
    "Claude Code spend tracker",
    "Cursor spend analytics",
    "AI token usage dashboard",
    "AI budget management for teams",
    "engineering cost visibility",
    "AI spend reconciliation",
  ],
  authors: [{ name: "PlanckSpace" }],
  openGraph: {
    title: "PlanckSpace — Spend management for AI-assisted engineering",
    description:
      "Meter every token across Claude Code, Cursor, Windsurf, and Antigravity. Cost visibility, waste detection, and invoice reconciliation — without touching your code.",
    type: "website",
    url: "https://planckspace.dev",
    siteName: "PlanckSpace",
    images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: "PlanckSpace" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "PlanckSpace — Spend management for AI-assisted engineering",
    description:
      "Meter every token across Claude Code, Cursor, Windsurf, and Antigravity. Cost visibility, waste detection, and invoice reconciliation — without touching your code.",
    images: [OG_IMAGE],
  },
  // Tab icons come from /favicon (generated by the frontend's scripts/gen-favicons.mjs),
  // not straight from the kit: the kit's favicons are the bare ink mark on transparency,
  // which disappears against a dark browser tab strip. These are the mark on an ink tile.
  icons: {
    icon: [
      { url: "/favicon/favicon.ico", sizes: "any" },
      { url: "/favicon/planckspace-favicon.svg", type: "image/svg+xml" },
      { url: "/favicon/favicon-48.png", sizes: "48x48", type: "image/png" },
      { url: "/favicon/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon/favicon-16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: { url: "/favicon/apple-touch-icon.png", sizes: "180x180" },
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geist.variable} ${jetbrains.variable} h-full`}>
      <body className="antialiased min-h-full bg-[var(--page)] text-[var(--ink)]">
        {children}
      </body>
    </html>
  );
}
